modLoader="lowcodefml"
loaderVersion="[1,)"
license="MIT License"
issueTrackerURL="https://github.com/brnbrd/CopperDrops/issues"

[[mods]]
modId="copperdrops"
version="${file.jarVersion}"
displayName="Copper Drops"
displayURL="https://www.curseforge.com/minecraft/mc-mods/copper-drops"
updateJSONURL="https://raw.githubusercontent.com/brnbrd/CopperDrops/1.20/update.json"
logoFile="copperdrops.png"
logoBlur=false
authors="brnbrd"
description="Decreases drops of Copper Ore to balance gameplay."
itemIcon="minecraft:raw_copper"
configBackground="minecraft:textures/block/cut_copper.png"

[[dependencies.copperdrops]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.copperdrops]]
    modId="ad_astra"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.copperdrops]]
    modId="deeperdarker"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.copperdrops]]
    modId="bno"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"